### ISSUE TITLE
Feature request : pass kwargs with TradingSignal

### ISSUE THREAD

**Issue by pinkgrass** [gbeced/basana#11]
GM.

Loved your previous work on PyAlgoTrade.
Basana is tremendous upgrade. Thank you.

Could you please extend the [TradingSignal](https://github.com/gbeced/basana/blob/master/basana/core/event_sources/trading_signal.py#L23) to allow kwargs to be passed. This allows the Strategy to pass other attributes than just the order operation and pair to the PositionManager?

This is useful when the strategy is passing a weighting to be bought/sold.

As an example, I have shown the [RSI example](https://github.com/gbeced/basana/blob/master/samples/rsi.py) extended to pass the `oversold` value in the TradingSignal:

```python
# RSI crossed below oversold level
if self.rsi[-2] >= self._oversold_level and self.rsi[-1] < self._oversold_level:
    self.push(bs.TradingSignal(bar_event.when, bs.OrderOperation.BUY, bar_event.bar.pair, oversold=self.rsi[-1]))
 # RSI crossed above overbought level
elif self.rsi[-2] <= self._overbought_level and self.rsi[-1] > self._overbought_level:
    self.push(bs.TradingSignal(bar_event.when, bs.OrderOperation.SELL, bar_event.bar.pair, oversold=self.rsi[-1]))
```

**Comment by henzycuong1** [comment]
+1

**Comment by gbeced** [comment]
@pinkgrass you achieve the same thing by extending TradingSignal and adding whatever you need to add.
