### ISSUE TITLE
DEVELOPER.md missing extra dependencies causes test suite failures

### ISSUE THREAD

**Issue by jxstanford** [gbeced/basana#24]
Following instructions in DEVELOPER.md results in test failures:

`
FAIL Required test coverage of 100.0% not reached. Total coverage: 41.25%
================================================================== short test summary info ==================================================================
ERROR tests/test_backtesting_charts.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 1 error in 0.57s ======================================================================
`

Specifying `poetry install --all-extras` in DEVELOPER.md resolves:

`
Required test coverage of 100.0% reached. Total coverage: 100.00%
=================================================================== slowest 10 durations ====================================================================
2.41s call     tests/test_bitstamp_bars.py::test_bars_from_trades
2.10s call     tests/test_backtesting_charts.py::test_save_line_chart[order_plan0]
1.02s call     tests/test_core_websockets.py::test_schedule_reconnection
1.00s call     tests/test_dispatcher.py::test_realtime_scheduler[1]
0.84s call     tests/test_binance_bars.py::test_bars
0.51s call     tests/test_dispatcher.py::test_realtime_scheduler[0.5]
0.50s call     tests/test_token_bucket.py::test_token_wait
0.38s call     tests/test_event.py::test_mutiple_sources
0.30s call     tests/test_dispatcher.py::test_out_of_order_events_are_skipped
0.26s call     tests/test_bitstamp_orders.py::test_authentication_fails
============================================================ 226 passed, 2523 warnings in 18.72s ============================================================

**Comment by gbeced** [comment]
Thanks!
