### ISSUE TITLE
idempotent cancel_order in backtesting exchange

### ISSUE THREAD

**Issue by jxstanford** [gbeced/basana#26]
Making cancel_order idempotent simplifies state management.

**Comment by gbeced** [comment]
In some cases that might be true, but I don't think that kind of behaviour should be inside this library. I rather prefer to treat invalid state transitions as an error, and let layers above decide wether to ignore that or not.

**Comment by jxstanford** [comment]
I can see it that way as well. I'll close the PR. Thanks for considering!
