### ISSUE TITLE
datetime.datetime.utcfromtimestamp() is deprecated 

### ISSUE THREAD

**Issue by dkoleary88** [gbeced/basana#32]
basana/external/binance/tools/download_bars.py:79: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).

**Comment by gbeced** [comment]
Fixed in https://github.com/gbeced/basana/commit/003130d5c578ebaf14cc8aea27343bc3f55c1479. It will be released in the next version. Thanks for the report.
