### ISSUE TITLE
Improve plot

### ISSUE THREAD

**Issue by femtotrader** [gbeced/basana#35]
Hello,

it could be a nice improvement to have such a plot ie plot of each owned stocks/cryptos/fiat over time.

![screenshot](https://github.com/gbeced/basana/assets/5049737/9ddf72b9-0a8b-4803-a8a7-e405adadefc6)

from [Blankly](https://blankly.finance/)

Kind regards

**Comment by gbeced** [comment]
Its not automatic, since the graphs may end up too cluttered, but it can be done using https://basana.readthedocs.io/en/latest/backtesting_charts.html#basana.backtesting.charts.LineCharts.add_balance
