### ISSUE TITLE
Can't run sample samples.backtest_bbands

### ISSUE THREAD

**Issue by TEPOTPOH** [gbeced/basana#42]
Hi, I tried to run example backtest_bbands, but got some errors.

After these commands
```
python3 -m venv venvbn
source venvbn/bin/activate
pip install basana[charts]
pip install talipp pandas statsmodels
python -m basana.external.binance.tools.download_bars -c BTC/USDT -p 1d -s 2021-01-01 -e 2021-12-31 -o binance_btcusdt_day.csv
python -m samples.backtest_bbands
```
got error
`/home/user/basana/venvbn/bin/python: Error while finding module specification for 'samples.backtest_bbands' (ModuleNotFoundError: No module named 'samples')`

It looks like there is no installed python module 'samples'.

I managed to run this example by downloading sources, made fix
replace
```
from samples.backtesting import position_manager
from samples.strategies import bbands
```
to
```
from backtesting import position_manager
from strategies import bbands
```
 and run this way
`python3 samples/backtest_bbands.py`

What I did I do wrong initially? or shouldn't this module 'samples' be installed before running examples? or may be better would be fix examples code?

**Comment by gbeced** [comment]
I just updated README.md with a link to samples.zip.
