### ISSUE TITLE
more feature ?

### ISSUE THREAD

**Issue by henzycuong1** [gbeced/basana#7]
Hi, do you have idea for order features like backtesting.py ? Like stoploss price, take profit price or I want order at the close price of the previous bar but class bs.TradingSignal just get 3 params.
`class TradingSignal(event.Event):
    """A trading signal is an event that instructs to buy or sell a given pair.

    :param when: The datetime when the trading signal occurred. It must have timezone information set.
    :param operation: The operation.
    :param pair: The pair to trade.
    """

    def __init__(self, when: datetime.datetime, operation: enums.OrderOperation, pair: pair.Pair):
        super().__init__(when)
        #: The operation.
        self.operation = operation
        #: The pair to trade.
        self.pair = pair`

**Comment by gbeced** [comment]
Please use the [discussion](https://github.com/gbeced/basana/discussions/new/choose) area if you're seeking for help.
